### ISSUE TITLE
"Error: Could not find addon with ID" - Not uninstalling the study addon when not eligable for Pioneer study

### ISSUE THREAD

**Issue by motin** [mozilla/pioneer-utils#29]
I am not sure if this is intended behavior, general to pioneer-utils or specific to https://github.com/motin/esper-pioneer-shield-study so bare with me, but when I [install the newly pioneer-utils-refactored add-on](https://github.com/motin/esper-pioneer-shield-study/blob/use-pioneer-utils/TESTPLAN.md) in a Firefox profile without the Pioneer Opt-in add-on, I get the following error from pioneer-utils when it tries to uninstall the add-on:

Error: Could not find addon with ID: esper-pioneer-shield-study@shield.mozilla.org  PioneerUtils.jsm:311:13

This is despite that the ID is the correct ID as shown in this screenshot: https://www.dropbox.com/s/k87nzk8wvfnsxj2/Screenshot%202017-11-23%2014.28.12.png?dl=0

Pioneer utils version 1.0.9

**Comment by rehandalal** [comment]
You have the wrong pioneer id in your `Config.jsm` file:

In https://github.com/motin/esper-pioneer-shield-study/blob/use-pioneer-utils/addon/Config.jsm#L8 you have:
```
"esper-pioneer-shield-study@shield.mozilla.org"
```

In https://github.com/motin/esper-pioneer-shield-study/blob/use-pioneer-utils/package.json#L8 you have:
```
"esper-pioneer-shield-study@shield.mozilla.com"
```

**Comment by motin** [comment]
Thank you! Silly mistake... Btw, we could avoid these mistakes altogether by not even having addonId in Config.jsm

**Comment by mythmon** [comment]
I've proposed a way to avoid needing to pass addonId in #30.
